### ISSUE TITLE
Tooltip disappears on bubble drilldown

### ISSUE THREAD

**Issue by gillesgerlo** [jbkunst/highcharter#358] opened 2017-08-28 00:56 UTC
More precisely, the tooltip formatting disappears when I drill back up to the highest level. I've slightly tweaked the standard drilldown example to make it a bubble chart, as the issue does not persist with column charts:

rm(list = ls())
suppressPackageStartupMessages(library("dplyr"))
suppressPackageStartupMessages(library("purrr"))
suppressPackageStartupMessages(library("highcharter"))

df <- data_frame(
  name = c("Animals", "Fruits", "Cars"),
  x = c(5, 2, 4),
  y = c(5, 2, 4),
  drilldown = tolower(name)
)

df

hc <- highchart() %>%
  hc_chart(type = "bubble") %>%
  hc_title(text = "Basic drilldown") %>%
  hc_xAxis(type = "category") %>%
  hc_legend(enabled = FALSE) %>%
  hc_tooltip(pointFormat = 'Test: {point.y}')  %>%
  hc_plotOptions(
    series = list(
      boderWidth = 0,
      dataLabels = list(enabled = TRUE)
    )
  ) %>%
  hc_add_series(
    data = df,
    name = "Things",
    colorByPoint = TRUE
  )

dfan <- data_frame(
  name = c("Cats", "Dogs", "Cows", "Sheep", "Pigs"),
  x = c(4, 3, 1, 2, 1),
  y = c(4, 3, 1, 2, 1)
)

dffru <- data_frame(
  name = c("Apple", "Organes"),
  x = c(4, 2),
  y = c(4, 2)
)

dfcar <- data_frame(
  name = c("Toyota", "Opel", "Volkswagen"),
  x = c(4, 2, 2),
  y = c(4, 2, 2)
)

hc <- hc %>%
  hc_drilldown(
    allowPointDrilldown = TRUE,
    series = list(
      list(
        id = "animals",
        data = list_parse2(dfan)
      ),
      list(
        id = "fruits",
        data = list_parse2(dffru)
      ),
      list(
        id = "cars",
        data = list_parse2(dfcar)
      )
    )
  )

hc

Any help would be really appreciated :)

**Comment by jbkunst** [comment] 2017-08-28 01:19
Hi @gillesgerlo ,

Are you using the dev version?

**Comment by gillesgerlo** [comment] 2017-08-28 03:44
Hi Joshua,

I now am :) The issue is still there though.

Cheers

**Comment by jbkunst** [comment] 2017-08-28 05:19
I think this is a highchartsJS behavior. I'll try to find some info.

**Comment by gillesgerlo** [comment] 2017-08-28 06:42
Thanks a lot, appreciate it.
I've never been able to figure this out myself.

**Comment by gillesgerlo** [comment] 2017-09-01 03:47
Were you able to find out anything? Alternatively, is there any way to have a button that re-renders/refreshes the whole chart? That would pretty much solve the problem.

Thanks!

**Comment by jbkunst** [comment] 2020-08-23 22:47
Hi @gillesgerlo 

I can't reproduce the problem. Look it's fixed in the current version.

![image](https://user-images.githubusercontent.com/56481/90990655-1aaf9080-e571-11ea-8d12-dac627808d8d.png)

**Closed by jbkunst** 2020-08-23 22:47 UTC
Labels: question, wontfix
