### ISSUE TITLE
Set Options: Comma Separator

### ISSUE THREAD

**Issue by ctmann** [jbkunst/highcharter#69] opened 2016-04-11 00:32 UTC
highchart() 'hc_opts' doesn't seem to implement languages, particularly: 

  Highcharts.setOptions({
    lang: {
      thousandsSep: ','
    }

Shouldn't it look like this?
highchart(debug = TRUE, hc_opts = list(lang = list(thousandsSep= ",") ))

http://api.highcharts.com/highcharts#lang.thousandsSep

**Comment by jbkunst** [comment] 2016-04-11 02:41
@ctmann 

It's implemented via options:

```
# get
hcopts <- getOption("highcharter.options")

# explore
hcopts

# override
hcopts$lang$thousandsSep <- "*"

# update
options(highcharter.options = hcopts)

# use!
highchart() %>% 
  hc_add_series(data = rnorm(100)*10000)
```

It seems I need to make some examples ;) using options.

Thanks for try the package.

**Comment by AristarXXX** [comment] 2016-04-11 07:18
Thanks for that topic! I had the same question about using UTC, but with this example it works just fine. Is it possible to do this some nice way without saving all options to list?

**Comment by jbkunst** [comment] 2016-04-11 12:42
@AristarXXX  

I'm not sure how you imagine the implementation. Maybe something like:

```
hcoptions$set(lang = list(thousandsSep  = "*"))
```

?.

Regards,

**Comment by jbkunst** [comment] 2016-04-12 13:18
I'll close the issue. If anyone want to discuss possible features, we'll reopen ;)

**Closed by jbkunst** 2016-04-12 13:18 UTC

**Comment by AristarXXX** [comment] 2016-04-12 19:48
Hi, Joshua! 
Something like this would be cool!
Or like you set global options for DT package with DT.options argument of options function. 

https://stat.ethz.ch/R-manual/R-devel/library/base/html/options.html

options(DT.options = list(pageLength = 5, language = list(search = 'Filter:')))

it's described here https://rstudio.github.io/DT/options.html in 3. Global Options.

Is it possible to do something like this?

11.04.2016, 15:42, "Joshua Kunst" <notifications@github.com>:
> @AristarXXX
>
> I'm not sure how you imagine the implementation. Maybe something like:
>
> hcoptions$set(lang = list(thousandsSep = "*"))
>
> ?.
>
> Regards,
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub

-- 
С уважением,
 Фирсов Константин

**Comment by jbkunst** [comment] 2016-04-12 20:49
@AristarXXX 

You can do the same:
```
options(highcharter.options = list(lang = list(thousandsSep  = "*")))
```

The problem is that highcharter don't use the same defaults than highcharts. So you override the default pacakge options which are not the same that highcharts options:

For example test:

```
library("highcharter")

# dont have title or credits
highchart() %>% 
  hc_add_series(data = rnorm(100)*10000)

options(highcharter.options = list(lang = list(thousandsSep  = "*")))

# have title and credits and the thousand separator
highchart() %>% 
  hc_add_series(data = rnorm(100)*10000)
```

That's why I extract the default highcharter options and modify only the part I want and the re-assing to the `highcharter.options`.

I think is a good choice implement options like knitr's style: ` hcoptions$set(...)`

**Comment by AristarXXX** [comment] 2016-04-12 20:57
Joshua, thank you for the explanation! I try it in console and now i see the difference. Now it is more clear to me. Thanks again for the reply. Highcharts is awesome and highcharter is awesome :) 

12.04.2016, 23:49, "Joshua Kunst" <notifications@github.com>:
> @AristarXXX
>
> You can do the same:
>
> options(highcharter.options = list(lang = list(thousandsSep = "*")))
>
> The problem is that highcharter don't use the same defaults than highcharts. So you override the default pacakge options which are not the same that highcharts options:
>
> For example test:
>
> library("highcharter") # dont have title or credits highchart() %>% hc_add_series(data = rnorm(100)*10000) options(highcharter.options = list(lang = list(thousandsSep = "*"))) # have title and credits and the thousand separator highchart() %>% hc_add_series(data = rnorm(100)*10000)
>
> That's why I extract the default highcharter options and modify only the part I want and the re-assing to the highcharter.options.
>
> I think is a good choice implement options like knitr's style: hcoptions$set(...)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub

-- 
С уважением,
 Фирсов Константин

**Comment by jbkunst** [comment] 2016-04-12 21:03
Whoa! Thanks and much more thanks for use the package ;)!

**Comment by ctmann** [comment] 2016-04-16 19:52
Thanks so much for this great package! More documentation, please!!!!!!
Does your answer describe setting graph options, as well? I would like to remove icons from all series in a graph:

    plotOptions: {
      area: {
        marker: {
          enabled: false,
          symbol: 'circle',
          radius: 2,
          states: {
            hover: {
              enabled: true
            }}}}}
          
Is this the highcharter implementation?
highchart(hc_plotOptions(area = list(marker = list(
                                       enabled = FALSE,
                                       symbol = 'square',
                                       radius = 2,
                                       states = list(
                                         hover = list(enabled = TRUE)
                                       )))))

**Comment by AristarXXX** [comment] 2016-04-19 18:02
Hi, Nettle! Your implementation looks fine.But if you do not want to use icons i think enabled = FALSE is all that you need. Like this:hc_plotOptions(area = list(marker = list(enabled = FALSE))) 16.04.2016, 22:52, "Nettle" <notifications@github.com>:Thanks so much for this great package! More documentation, please!!!!!! Does your answer describe setting graph options, as well? I would like to remove icons from all series in a graph:plotOptions: {
  area: {
    marker: {
      enabled: false,
      symbol: 'circle',
      radius: 2,
      states: {
        hover: {
          enabled: true
        }}}}}
Is this the highcharter implementation? highchart(hc_plotOptions(area = list(marker = list( enabled = FALSE, symbol = 'square', radius = 2, states = list( hover = list(enabled = TRUE) )))))—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub   -- С уважением, Фирсов Константин

**Comment by ctmann** [comment] 2016-04-30 22:12
CRAN version supports earlier solution (below), but GitHub version no longer works. Is there a new way for putting commas in labels, or is this a bug?

```
hcopts <- getOption("highcharter.options")
hcopts$lang$thousandsSep <- "*"
options(highcharter.options = hcopts)

highchart() %>% 
hc_add_series(data = rnorm(100)*10000)

```

**Comment by jbkunst** [comment] 2016-05-01 01:29
Hi @ctmann 

Yep, in #77 I changed/separated the options list. So;

```
hcoptslang <- getOption("highcharter.lang")
hcoptslang$thousandsSep <- "*"
options(highcharter.lang = hcoptslang)

highchart() %>% 
  hc_add_series(data = rnorm(100)*10000)
```

This will be documented in the NEWS of the next release ;)!

Regards,

**Comment by chenx2018** [comment] 2019-09-04 09:23
This approach does not work in Shiny apps. ANY suggestion?

**Comment by jbkunst** [comment] 2019-09-04 13:59
@chenx2018 

I need a reprex -reproducible example- for test, can you create one?
