### ISSUE TITLE
Correlation matrix with Highchart heatmap (hchart.matrix)

### ISSUE THREAD

**Issue by adymimos** [jbkunst/highcharter#86] opened 2016-04-27 00:07 UTC
It would be great if you can add a function which gives correlation matrix with highchart heatmap.
Is it possible to create one?

**Comment by jbkunst** [comment] 2016-04-27 02:30
@adymimos 

Obviously this is possible :wink:. I'll put this on the enhancement tag. If you have a *mockup* code to start from there is very welcome if not the case I'll take some time the next week. I think this wont be hard, we need to reuse https://github.com/jbkunst/highcharter/blob/master/R/hchart.R#L220

**Comment by 4d1in3** [comment] 2016-04-27 02:39
I have an implementation highcharts with rCharts. But it is not as good as one with polycharts [http://rcharts.io/viewer/?7073094#.VyAiXrO_vEU]. With highchart color gradient always screws up. Let me try to make an example with dist

**Comment by adymimos** [comment] 2016-04-27 05:40
@jbkunst 
Thanks for the pointer. I was able to implement it.

http://rpubs.com/adymimos/176226

pls let me know if you require this as a new function, I can create a pull request

**Comment by jbkunst** [comment] 2016-04-27 18:20
Nice @adymimos :smile: ile:!

Mmm not sure how include this function becuase `class(cor(mtcars))` is matrix. Maybe is a good/reasonable alternative if we make heatmaps to chart matrix in the `hchart` function by default. 

Can you make a pull request modifying `hchart.R` file and creating `hchart.matrix(object, ...)` function with your code? Are you agree? If you do, modify DESCRIPTION file adding you name as ctb.

Thanks and regards,

**Comment by jbkunst** [comment] 2016-05-23 20:59
Closed by @adymimos in #108

**Closed by jbkunst** 2016-05-23 20:59 UTC
Labels: enhancement

**Comment by jrounds** [comment] 2016-06-15 03:07
http://rpubs.com/adymimos/176226

In my browser the "-1" in the legend is cut off.  Is there anyway to pad it so the -1 doesn't get cut off?

**Comment by jbkunst** [comment] 2016-06-24 16:47
Hi @jrounds ,

Sorry for the late reponse.

I think the issue is caused by some options given by @adymimos in the `hchart.matrix` in the legend option, I removed them so highcharter will use the default ones.

You can check the result here:  http://rpubs.com/jbkunst/highcharter-issue-86

Thanks!
