### ISSUE TITLE
hc_exporting() disconnects Shiny session in Firefox

### ISSUE THREAD

**Issue by schmockolaus** [jbkunst/highcharter#131] opened 2016-06-17 13:38 UTC
Thank you for providing this great library! 

I have encountered the problem that when I use client-side export (`hc_exporting(enabled = TRUE)`) in Firefox, the Shiny session gets disconnected, regardless of the export format. In other browsers (Chrome, Safari), it works like expected. 

Do you have any ideas why this might happen? The JavaScript console only states that the websocket connection was interrupted. I use RStudio v0.99.902, R v3.3.0, shiny v0.13.2, highcharter v0.3.0, Firefox v44 (Ubuntu) and v47 (OS X).

Here is some example code:
```R
library("shiny")
library("highcharter")
data(citytemp)

ui <- fluidPage(
    column(width = 12,
           highchartOutput("hcontainer",height = "500px")
    )
)

server = function(input, output) {
  output$hcontainer <- renderHighchart({
    hc <- hc_demo() %>%
      hc_exporting(enabled=TRUE)
    hc
  })
}

shinyApp(ui = ui, server = server)
```
Thanks!

**Comment by jwinter6** [comment] 2016-06-17 15:04
I also observe this behavior, so I think this is an issue of how this is dealt with by the browser.
As we could not fix it, I wonder if we can set it to server-side exporting (locally)?

**Comment by jbkunst** [comment] 2016-06-17 15:51
Mmm... ok, I'll check it.

I see firefox dont love highcharts so much: http://stackoverflow.com/questions/26679450/highcharts-not-combatible-with-firefox-solved, http://stackoverflow.com/questions/29394805/black-image-bug-when-exporting-highcharts-in-firefox XD, 

@jwinter6  About the server side exporting, you can track issue #126

**Comment by jbkunst** [comment] 2016-07-08 20:54
Hi, @schmockolaus @jwinter6 

Hi I made some changes in the yaml and I tested in firefox and dont have problems. Can you check please :)? Thanks!

**Comment by schmockolaus** [comment] 2016-07-11 09:05
Seems to work now (tested on Firefox 47.0, OS X 10.11). Thank you very much for fixing this!
However, with highcharter 0.3.0 (cran version) I could choose from PDF, SVG, JPEG, and PNG as download format, the most recent github version only offers PNG and SVG.

**Comment by joh024** [comment] 2016-07-11 14:37
I believe the issue is that firefox tries to navigate to the exporting server page (hence disconnecting from shiny server). It can be resolved by adding `formAttributes = list(target = "_blank")`, e.g.

```R
hc_exporting(enabled = TRUE, formAttributes = list(target = "_blank"))
```

This is for the current CRAN version (the one that does not use client-side exporting).

**Comment by jbkunst** [comment] 2016-07-11 18:58
I tested without the client side exporting and the code provide by @joh024  solve the issue in my case. So as @joh024 recommend we reverse this chage (add `offline-exporing.js`).

**Comment by jbkunst** [comment] 2016-07-21 14:31
Ok, let's cloe the issue!

**Closed by jbkunst** 2016-07-21 14:31 UTC
Labels: question

**Comment by nuno-agostinho** [comment] 2016-12-16 11:59
Hi @jbkunst! It seems I'm having the issue with the most recent version of Highcharts available in CRAN (0.4.0). This issue was not solved for this version?

**Comment by jbkunst** [comment] 2016-12-16 15:00
Hi @nuno-agostinho ! ;D.

Not sure, sorry, 0.4.0 was release on 12 Jul (https://github.com/jbkunst/highcharter/releases/tag/v0.4.0) and the issue start on Jun but it was close the 21 Jul.  And the las commit was 11 Jul (https://github.com/jbkunst/highcharter/issues/131#issuecomment-231830794)

Do you have the issue with the dev version?

**Comment by nuno-agostinho** [comment] 2016-12-16 16:07
No, the dev version works as expected. I only wanted to confirm as this was close to the release version. Thank you for your help! :)
