### ISSUE TITLE
hc_add_annotations() not working for developer version

### ISSUE THREAD

**Issue by tedhwang** [jbkunst/highcharter#392] opened 2018-01-30 16:06 UTC
Hi, 

I downloaded developer version yesterday to make use of highchart2() and found that hc_add_annotations() doesn't work as usual. Could you check if this is really the issue with the newer version or a mistake from my side. (I could provide my example code if you'd like)

Thanks.

**Comment by jbkunst** [comment] 2018-01-30 16:19
Hi @tedhwang 

Yes, there are some changes due highchartsjs (v6) have an annotation module, so the (old) pluging is not required.

You can a related question and an example here https://stackoverflow.com/questions/47935128/highcharter-annotation-on-date-x-axis-not-working-r/48425405#48425405

Tell me if this help you!

**Comment by tedhwang** [comment] 2018-01-30 16:40
Hi @jbkunst 

After appropriately applying the code in the example, I get 'Error: All arguments must be named list'. 

I'm using highchart2() %>% hc_add_series_list() for speed concerns. Do you think not using hchart() could have caused the error? 

Thanks for the quick feedback btw. (really appreciate it!)

**Comment by jbkunst** [comment] 2018-01-30 17:47
Mmm... Let's work with a reproducible example. Can you post one?

**Comment by tedhwang** [comment] 2018-01-30 19:27
library(highcharter)
library(dplyr)
library(data.table)

df<- data.table(x=1:10,y= c(rep(5,5),rep(10,5)), caption=c("line 1","line 2" ))

df_2 <- df %>% 
  group_by(y) %>% 
  do(data = list_parse(.)) %>%
  mutate(type = "line") %>%
  #mutate(yAxis=1) %>%
  rename(name=y)

hc <- 
  highchart2( ) %>% 
  hc_add_series_list(df_2)# %>%


# annotation method 1 (from your example)
hc <- 
hc %>% 
  hc_annotations(
    list(
      labelOptions = list(y = 7.5, x = 5),
      labels = list(
        list(
          point = list(
            x = 5,
            y = 7.5
            ,yAxis = 0
          ),
          text = "hi"
        )
      )
    )
  )

hc
# annotation method 2 (the way it used to work for me)

annotation.tbl <- data.table(xValue=c(3,8) ,yValue=c(5,10), yAxis=0,title=c("hello","how are you")) 
annotation.tbl$title <- lapply(annotation.tbl$title ,function(x) list(text = x,style = list(color="skyblue",fontSize=25  )))

hc <- hc %>% hc_add_annotation(annotation.tbl)
hc

#I'm not sure if this is a good way of adding a code. Let me know if there is another approach. Thx!

**Comment by tedhwang** [comment] 2018-01-30 19:28
`
library(highcharter)
library(dplyr)
library(data.table)

df<- data.table(x=1:10,y= c(rep(5,5),rep(10,5)), caption=c("line 1","line 2" ))

df_2 <- df %>% 
  group_by(y) %>% 
  do(data = list_parse(.)) %>%
  mutate(type = "line") %>%
  #mutate(yAxis=1) %>%
  rename(name=y)

hc <- 
  highchart2( ) %>% 
  hc_add_series_list(df_2)# %>%


# annotation method 1 (from your example)
hc <- 
hc %>% 
  hc_annotations(
    list(
      labelOptions = list(y = 7.5, x = 5),
      labels = list(
        list(
          point = list(
            x = 5,
            y = 7.5
            ,yAxis = 0
          ),
          text = "hi"
        )
      )
    )
  )

hc
# annotation method 2 (the way it used to work for me)

annotation.tbl <- data.table(xValue=c(3,8) ,yValue=c(5,10), yAxis=0,title=c("hello","how are you")) #.5 means middle
annotation.tbl$title <- lapply(annotation.tbl$title ,function(x) list(text = x,style = list(color="skyblue",fontSize=25  )))

hc <- hc %>% hc_add_annotation(annotation.tbl)
hc

`

**Comment by jbkunst** [comment] 2018-01-30 19:54
If you can format your post a bit :sweat_smile: it would be nice :smile:

**Comment by tedhwang** [comment] 2018-01-30 20:08
My apology (I'm new to Github) Hope this helps! :)

**Comment by tedhwang** [comment] 2018-01-31 16:26
Hi jbkunst, never trying to hurry you but was wondering if there's any updates. Were you able to get any better results?

**Comment by jbkunst** [comment] 2018-02-21 18:58
Hi @tedhwang 

1e100 sorry for the delay.

You can use `highchart` or `hchart`  now because include de boost module by default. Remember: the boost module is not for generate a htmlwidget quickly but to don´t have perfomance problems with tooltips when you load a lot of points. See  https://github.com/jbkunst/highcharter/issues/264#issuecomment-278848430

By other hand, `highcharts2` don't have many modules attached, so you cand use `hc_add_dependency` to add the annotation module: 

```r
# annotation method 1 (from your example)
hc <- 
  hc %>% 
  hc_annotations(
    list(
      labelOptions = list(y = 7.5, x = 5),
      labels = list(
        list(
          point = list(
            x = 5,
            y = 7.5 ,yAxis = 0
          ),
          text = "hi"
        )
      )
    )
  )

hc %>% 
  hc_add_dependency("modules/annotations.js")
```

![image](https://user-images.githubusercontent.com/56481/36499394-dc912f88-171f-11e8-9bec-ef3ed7f7547a.png)

**Comment by jbkunst** [comment] 2018-02-22 21:39
@tedhwang 

I'll close the issue but we can reopen if is needed ;)!

**Closed by jbkunst** 2018-02-22 21:39 UTC
Labels: question

**Comment by tedhwang** [comment] 2018-02-22 21:48
Awesome, thanks Joshua for clarification.

Can I ask last questions?

   - Is there any advantage in using highchart2() over highchart() now?
   Will highchart2() be default after official package update?
   - Is hc_add_series_list() still faster than hchart()?
   - I found a huge speed advantage so far,  but won't that be true in the
      future?

Thanks!

-Ted
