### ISSUE TITLE
dateTimeLabelFormats not working with R

### ISSUE THREAD

**Issue by hueanhpt** [jbkunst/highcharter#268] opened 2017-02-16 04:12 UTC
Dear sir,

I tried to using dateTimeLabelFormats argument of hc_xAxis to format datetime labels for axis but unfortunately the labels not display as format.

So, the R code is something like:
```
# Create data frame
df <-
  data_frame(time = seq(as.Date("2017-01-01"), as.Date("2017-02-01"), by = 1),
             value = sample(1000:2000, size = 32))

# Show chart
hc <-
  highchart() %>%
  hc_xAxis(categories = df$time,
           dateTimeLabelFormats = list(month = "%b", day = "%b") 
  ) %>%
  hc_add_series(data = df$value, name = "value")
hc
```

How could I fix the problem ?

**Comment by jbkunst** [comment] 2017-02-22 18:12
Hi @hueanhpt 

First of all when you use `categories = df$time` you are treating the data as categorical instead of `datetime`, you need something like this:

```r
# Create data frame
df <-
  data_frame(time = seq(as.Date("2017-01-01"), as.Date("2017-02-01"), by = 1),
             value = sample(1000:2000, size = 32),
             dt = datetime_to_timestamp(time))

# Show chart
highchart() %>%
  hc_xAxis(type = "datetime", dateTimeLabelFormats = list(day = '%d of %b')) %>%
  hc_add_series(df, "line", hcaes(dt, value))

# or:
# using hchart datetime are detected and the type of axis
# is changed
hchart(df, "line",  hcaes(dt, value)) 
  hc_xAxis(type = "datetime", dateTimeLabelFormats = list(day = '%d of %b')) 

```

![image](https://cloud.githubusercontent.com/assets/56481/23225561/0907da18-f911-11e6-8f44-b763e53e415b.png)

You need see the chart in a wide space to see the label. See http://api.highcharts.com/highstock/xAxis.dateTimeLabelFormats:

> For a datetime axis, the scale will automatically adjust to the appropriate unit. This member gives the default string representations used for each unit. For intermediate values, different units may be used, for example the day unit can be used on midnight and hour unit be used for intermediate values on the same axis. For an overview of the replacement codes, see dateFormat. Defaults to:
```
{
	millisecond: '%H:%M:%S.%L',
	second: '%H:%M:%S',
	minute: '%H:%M',
	hour: '%H:%M',
	day: '%e. %b',
	week: '%e. %b',
	month: '%b \'%y',
	year: '%Y'
}
```

**Comment by jbkunst** [comment] 2017-02-22 20:55
I'll close the issue, we can reopen if is needed :wink:

**Closed by jbkunst** 2017-02-22 20:55 UTC
Labels: question

**Comment by tonyk7440** [comment] 2018-02-21 13:00
Hi @jbkunst 
I've tried the above code but it seems like the date labels no longer work, is this functionality still supported?

package version: highcharter_0.5.0

```
df <-
  data_frame(time = seq(as.Date("2017-01-01"), as.Date("2017-02-01"), by = 1),
             value = sample(1000:2000, size = 32),
             dt = datetime_to_timestamp(time))

hchart(df, "line",  hcaes(dt, value)) 
  hc_xAxis(type = "datetime", dateTimeLabelFormats = list(day = '%d of %b')) 
```

**Comment by jbkunst** [comment] 2018-02-21 14:51
Hi @tonyk7440 ,

Can you put an image of what you get and tell what you expect?

**Comment by tonyk7440** [comment] 2018-02-21 14:57
I would expect to get:
![image](https://user-images.githubusercontent.com/4944073/36486845-70b0ba3e-1717-11e8-8093-59e4838a744d.png)


But I get the following:
![image](https://user-images.githubusercontent.com/4944073/36486827-6236686e-1717-11e8-907f-a8c2f537a75a.png)

Notice that the custom formatting of x-axis labels is not working in my example

**Comment by jbkunst** [comment] 2018-02-21 19:55
@tonyk7440 

What you're seeing is the week format. Try to expand the chart and you will see the expected result. 

So you need to add the 'week = '%d of %b' value in the list of the `dateTimeLabelFormats ` argument.

Please, try this examples and change the wide of the chart to see what happens
```r

df <- data_frame(
  time = seq(as.Date("2017-01-01"), as.Date("2017-02-01"), by = 1),
  value = sample(1000:2000, size = 32),
  dt = datetime_to_timestamp(time)
  )

hchart(df, "line",  hcaes(dt, value)) %>% 
  hc_xAxis(type = "datetime", dateTimeLabelFormats = list(day = '%d dayview', week = '%d weekview')) 

hchart(df, "line",  hcaes(dt, value)) %>% 
  hc_xAxis(type = "datetime", dateTimeLabelFormats = list(day = '%d of %b', week = '%d of %b')) 
```

**Comment by tonyk7440** [comment] 2018-02-22 15:12
Works perfect, thank you @jbkunst !

**Comment by MERE55** [comment] 2020-05-13 23:34
Trying to format the dates in the x axis using:
hc_xAxis(type = "datetime", dateTimeLabelFormats = list(day = '%d.%m.%Y'))
I would expect the dates being displayed like 20.04.2020 but 20. Apr is displayed instead.
Using hc_tooltip(xDateFormat = "%d.%m,%Y") for tooltip is working fine.
What did I wrong ?

**Comment by tonyk7440** [comment] 2020-05-14 10:14
Hi @MERE55 , not sure where the problem is, can you make a reproducible example to make helping easier? https://www.tidyverse.org/help/

**Comment by MERE55** [comment] 2020-05-14 11:25
Hi @tonyk7440 , I will just send you my data, the R code used and the resulting HTML. As you can see in the resulting plot the date in the x axis is not shown in the defined format %d.%m.%Y
[MERE55.zip](https://github.com/jbkunst/highcharter/files/4627939/MERE55.zip)
Hope this helps to show my issue.
Thx a lot for looking at it :-)

**Comment by dihesus** [comment] 2020-06-02 11:49
> @tonyk7440
> 
> What you're seeing is the week format. Try to expand the chart and you will see the expected result.
> 
> So you need to add the 'week = '%d of %b' value in the list of the `dateTimeLabelFormats ` argument.
> 
> Please, try this examples and change the wide of the chart to see what happens and read http://api.highcharts.com/highstock/xAxis.dateTimeLabelFormats ;)!
> 
> ```r
> df <- data_frame(
>   time = seq(as.Date("2017-01-01"), as.Date("2017-02-01"), by = 1),
>   value = sample(1000:2000, size = 32),
>   dt = datetime_to_timestamp(time)
>   )
> 
> hchart(df, "line",  hcaes(dt, value)) %>% 
>   hc_xAxis(type = "datetime", dateTimeLabelFormats = list(day = '%d dayview', week = '%d weekview')) 
> 
> hchart(df, "line",  hcaes(dt, value)) %>% 
>   hc_xAxis(type = "datetime", dateTimeLabelFormats = list(day = '%d of %b', week = '%d of %b')) 
> ```

@jbkunst  Thank you. This worked for me. If after implementing the above solution and still doesn't work, try increasing the width of your chart.
